#!/usr/bin/env bash

set -e


ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PROJECTS_DIR="$ROOT_DIR/Projects"

TEMPLATES_DIR="$ROOT_DIR/templates"


source "$ROOT_DIR/lib/colours.sh"
source "$ROOT_DIR/lib/banner.sh"


validate_template()
{
    FILE=$1

    if [ ! -f "$FILE" ]; then

        echo -e "${RED}❌ Missing template:${RESET}"
        echo "$FILE"
        exit 1

    fi


    if [ ! -s "$FILE" ]; then

        echo -e "${RED}❌ Empty template:${RESET}"
        echo "$FILE"
        exit 1

    fi
}


banner


echo -e "${CYAN}Validating Dock-Rust templates...${RESET}"


validate_template "$TEMPLATES_DIR/frontend/package.json"

validate_template "$TEMPLATES_DIR/backend/Cargo.toml"

validate_template "$TEMPLATES_DIR/docker/backend.Dockerfile"

validate_template "$TEMPLATES_DIR/docker/frontend.Dockerfile"

validate_template "$TEMPLATES_DIR/docker/docker-compose.yml"


echo -e "${GREEN}✔ Templates valid${RESET}"

echo


echo -e "${CYAN}Create a new Dock-Rust project${RESET}"

echo


read -r -p "Project name: " PROJECT_NAME


if [ -z "$PROJECT_NAME" ]; then

    echo -e "${RED}❌ Project name cannot be empty${RESET}"
    exit 1

fi


if [[ "$PROJECT_NAME" =~ [^a-zA-Z0-9_-] ]]; then

    echo -e "${RED}❌ Invalid project name${RESET}"
    echo "Only letters, numbers, '-' and '_' are allowed."
    exit 1

fi


mkdir -p "$PROJECTS_DIR"


PROJECT_PATH="$PROJECTS_DIR/$PROJECT_NAME"


if [ -d "$PROJECT_PATH" ]; then

    echo
    echo -e "${YELLOW}⚠ Project already exists${RESET}"
    echo "$PROJECT_PATH"
    echo


    read -r -p "Continue and overwrite files? (y/n): " CONFIRM


    if [[ "$CONFIRM" != "y" ]]; then

        exit 0

    fi

fi


echo

echo -e "${CYAN}Creating project: $PROJECT_NAME${RESET}"

echo


mkdir -p "$PROJECT_PATH"


cd "$PROJECT_PATH"


echo -e "${CYAN}Creating directories...${RESET}"


mkdir -p \
database \
redis \
testing \
docker/postgres


echo -e "${GREEN}✔ Directories created${RESET}"


echo


echo -e "${CYAN}Copying frontend template...${RESET}"


mkdir -p frontend

cp -R "$TEMPLATES_DIR/frontend/"* frontend/


echo -e "${GREEN}✔ Next.js + Bun frontend created${RESET}"


echo


echo -e "${CYAN}Copying backend template...${RESET}"


mkdir -p backend

cp -R "$TEMPLATES_DIR/backend/"* backend/


echo -e "${GREEN}✔ Rust backend created${RESET}"


echo


echo -e "${CYAN}Copying Docker configuration...${RESET}"


mkdir -p docker/postgres


cp "$TEMPLATES_DIR/docker/backend.Dockerfile" docker/

cp "$TEMPLATES_DIR/docker/frontend.Dockerfile" docker/

cp "$TEMPLATES_DIR/docker/docker-compose.yml" .

cp "$TEMPLATES_DIR/docker/postgres/init.sql" docker/postgres/


echo -e "${GREEN}✔ Docker configuration created${RESET}"


echo


echo -e "${CYAN}Creating environment files...${RESET}"


cat > .env <<EOF
PROJECT_NAME=$PROJECT_NAME

POSTGRES_USER=appuser
POSTGRES_PASSWORD=apppassword
POSTGRES_DB=appdb

DATABASE_HOST=database
DATABASE_PORT=5432

REDIS_HOST=redis
REDIS_PORT=6379
EOF


cp .env .env.example


echo -e "${GREEN}✔ Environment created${RESET}"


echo


echo -e "${CYAN}Creating project documentation...${RESET}"


cat > README.md <<EOF
# $PROJECT_NAME

Generated by Dock-Rust.


## Stack

Frontend:
- Next.js
- Bun


Backend:
- Rust
- Axum


Infrastructure:
- PostgreSQL
- Redis
- Docker


## Commands

Start:

\`\`\`bash
./dock-rust.sh up $PROJECT_NAME
\`\`\`

Stop:

\`\`\`bash
./dock-rust.sh down $PROJECT_NAME
\`\`\`
EOF


cat > .gitignore <<EOF
.env

node_modules
.next

target

*.log

.DS_Store

.vscode
.idea
EOF


echo -e "${GREEN}✔ Documentation created${RESET}"


echo


echo -e "${CYAN}Validating generated Docker setup...${RESET}"


if docker compose config >/dev/null 2>&1; then

    echo -e "${GREEN}✔ Docker configuration valid${RESET}"

else

    echo -e "${RED}❌ Docker configuration invalid${RESET}"

    docker compose config

    exit 1

fi


echo

echo -e "${GREEN}Project created successfully${RESET}"

echo

echo "Location:"
echo "$PROJECT_PATH"

echo

echo "Next step:"
echo

echo "./dock-rust.sh up $PROJECT_NAME"