import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
    title: "Dock-Rust",
    description: "Generated by Dock-Rust"
};


export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body suppressHydrationWarning>
                {children}
            </body>
        </html>
    );

}