{
 "title": "InfraOps Lab",
 "tags": [
  "infra",
  "ops",
  "lab"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "demo-app up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\\\"demo-app\\\"})"
    }
   ]
  },
  {
   "title": "probe success",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(probe_success)" }
   ]
  },
  {
   "title": "demo-app 5xx rate (%)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "100 * (sum(rate(demo_app_requests_total{status=~\\\"5..\\\"}[5m])) / clamp_min(sum(rate(demo_app_requests_total[5m])), 1))"
    }
   ]
  },
  {
   "title": "demo-app latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_app_request_duration_seconds_bucket{path=\\\"/\\\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Top container CPU (rate/sec)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{image!=\\\"\\\"}[5m])) by (name))"
    }
   ]
  },
  {
   "title": "Top container memory (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "topk(10, max(container_memory_working_set_bytes{image!=\\\"\\\"}) by (name))"
    }
   ]
  },
  {
   "title": "demo-app logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=\\\"demo-app\\\"}"
    }
   ]
  }
 ]
}